Aaina.Web/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Aaina.Common;
using Aaina.Data.Models;
using Aaina.Dto;
using Aaina.Service;
using Aaina.Web.Code;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using OfficeOpenXml;
using OfficeOpenXml.Style;

namespace Aaina.Web.Controllers
{
    public class ProjectController : BaseController
    {
        private readonly ILookService lookService;
        private readonly IGameService gameService;
        private readonly IGameFeedbackService service;
        private readonly IWeightageService weightageService;
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly IFilterService filterService;
        public ProjectController(IGameFeedbackService service, ILookService lookService, IGameService gameService, IWeightageService weightageService, IHostingEnvironment hostingEnvironment)
        {
            this.service = service;
            this.lookService = lookService;
            this.gameService = gameService;
            this.weightageService = weightageService;
            this._hostingEnvironment = hostingEnvironment;
            FileOutputUtil.OutputDir = new DirectoryInfo(hostingEnvironment.WebRootPath + "/TempExcel");
        }

        public IActionResult Index()
        {
            AddPageHeader("Game", "List");
            var all = gameService.GetAll(CurrentUser.CompanyId);
            return View(all);
        }

        public async Task<IActionResult> GameFeebBack(int tenant, int? lookId)
        {


            var menu = PermissionHelper.GetPermission(CurrentUser.UserId);
            LeftMenuDto leftMenu = JsonConvert.DeserializeObject<LeftMenuDto>(menu);
            if (string.IsNullOrEmpty(menu) || leftMenu == null || leftMenu.LeftMenu == null || !leftMenu.LeftMenu.Any())
            {
                leftMenu = new LeftMenuDto();
                var gamemenu = await gameService.GetMenuNLevel(CurrentUser.CompanyId);
                leftMenu.LeftMenu = gamemenu;
                leftMenu.EmojiList = weightageService.GetAllActive(CurrentUser.CompanyId);
                leftMenu.LeftUserMenuStatic = await gameService.GetUserMenuStatic(CurrentUser.UserId);
            }

            leftMenu.LeftMenuStatic = await gameService.GetMenuStatic(CurrentUser.UserId, tenant);

            PermissionHelper.SetPermission(JsonConvert.SerializeObject(leftMenu), CurrentUser.UserId);


            GameGridFeedbackDto model = new GameGridFeedbackDto() { GameId = tenant };
            model.EmojiList = weightageService.GetAllActive(CurrentUser.CompanyId);
            var deails = await gameService.GetDetailsId(tenant);
            model.GameName = deails.Name;

            var lookList = lookService.GetAllDrop(tenant, CurrentUser.CompanyId, CurrentUser.UserId);
            if (!lookId.HasValue && lookList.Any())
            {
                lookId = int.Parse(lookList.FirstOrDefault().Id);

            }

            if (lookId.HasValue)
            {
                model.LookList = lookList;
                model.LookId = lookId.Value;

                var look = await lookService.GetDetailsId(lookId.Value);

                if (look.TypeId == (int)LookType.Game)
                {
                    model.AllGames = gameService.GetAllByParentId(tenant, CurrentUser.CompanyId);
                    model.Feedbacks = await lookService.GetGameFeedback(tenant, lookId.Value, null, model.AttributeId, null, DateTime.Now);
                }

                else if (look.TypeId == (int)LookType.Team)
                {
                    model.AllGames = lookService.GetLookByLookId(lookId.Value);
                    model.Feedbacks = await lookService.GetTeamFeedback(tenant, lookId.Value, null, model.AttributeId, null, DateTime.Now);
                }

                else if (look.TypeId == (int)LookType.User)
                {
                    model.AllGames = lookService.GetUserByLookId(lookId.Value);
                    model.Feedbacks = await lookService.GetUserFeedback(tenant, lookId.Value, null, model.AttributeId, null, DateTime.Now);
                }
                model.LookGroupList = lookService.GetGroupAllDrop(lookId.Value, null, null);

            }
            ViewBag.id = tenant;
            return View(model);
        }

        public async Task<IActionResult> Feedback(int tenant, int? lookId, string pid)
        {
            LookFeebbackDto model = new LookFeebbackDto();
            List<int> gameId = new List<int>();

            if (!string.IsNullOrEmpty(pid))
            {
                gameId = pid.Split(",").Select(x => int.Parse(x)).ToList();
            }

            if (lookId.HasValue)
            {
                model = lookService.GetLookFeedbackByLookId(lookId.Value, CurrentUser.CompanyId, gameId);

                if (await service.IsDraftExist(lookId.Value, CurrentUser.UserId) || await service.IsDraftExistTeam(lookId.Value, CurrentUser.UserId) || await service.IsDraftExistUser(lookId.Value, CurrentUser.UserId))
                //if (true)
                {
                    if (model.TypeId == (int)LookType.Game)
                    {
                        GameFeedbackDto feedbackDto = await service.GetGameByLookId(lookId.Value, gameId, CurrentUser.UserId);
                        model.feedbackId = feedbackDto.Id;
                        model.GameFeedbackDetails = feedbackDto.GameFeedbackDetails;
                    }
                    else if (model.TypeId == (int)LookType.Team)
                    {
                        GameFeedbackDto feedbackDto = await service.GetTeamByLookId(lookId.Value, gameId, CurrentUser.UserId);
                        model.feedbackId = feedbackDto.Id;
                        model.GameFeedbackDetails = feedbackDto.GameFeedbackDetails;
                    }
                    else if (model.TypeId == (int)LookType.User)
                    {
                        GameFeedbackDto feedbackDto = await service.GetUserByLookId(lookId.Value, gameId, CurrentUser.UserId);
                        model.feedbackId = feedbackDto.Id;
                        model.GameFeedbackDetails = feedbackDto.GameFeedbackDetails;
                    }

                }
            }
            else
            {
                var gdata = await gameService.GetDetailsId(tenant);
                model.Game = gdata.Name;
                model.GameId = gdata.Id;
            }

            //model.LookList = lookService.GetAllDrop(gid, CurrentUser.CompanyId, CurrentUser.UserId);
            model.LookList = lookService.GetAllDropPrimission(tenant, CurrentUser.CompanyId, CurrentUser.UserId);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Feedback(GameFeedbackDto model)
        {
            if (model.GameFeedbackDetails.Count(a => a.GameId.HasValue && a.AttributeId.HasValue && a.SubAttributeId.HasValue && a.Feedback.HasValue) == 0)
            {
                ModelState.AddModelError("", "Feedback not valid");
                return CreateModelStateErrors();
            }
            model.CompanyId = CurrentUser.CompanyId;
            model.UserId = CurrentUser.UserId;
            if (model.TypeId == (int)LookType.Game)
            {
                await service.AddUpdateGameAsync(model);
            }
            else if (model.TypeId == (int)LookType.Team)
            {
                await service.AddUpdateTeamAsync(model);
            }
            else if (model.TypeId == (int)LookType.User)
            {
                await service.AddUpdateUserAsync(model);
            }
            return Json(new RequestOutcome<string> { RedirectUrl = Url.Action("Feedback", new { tenant = model.GameId }), IsSuccess = true });

        }


        [HttpPost]
        public async Task<IActionResult> ShareExcel(List<string> users, int tenant, int? lookId, int? presetId, int? atterbuteId, int? filterId)
        {
            try
            {
                string allusersEmails = string.Join(";", users);
                string html = "meeting link";
                var attachments = new Dictionary<string, byte[]>();
                var feeedbackModel = await GetFeedbackData(tenant, lookId, presetId, atterbuteId, filterId);
                string FileName = string.Empty;
                var newFile = FeedbackExportExcel(feeedbackModel, out FileName);
                // attachments.Add(MimeEntity.Load(newFile.FullName));
                byte[] myFileAsByteArray = Common.Common.FileToByteArray(newFile.FullName);
                attachments.Add(newFile.FullName, myFileAsByteArray);

                Common.Common.SendMailWithAttachment(allusersEmails, "Share", html, attachments);
                ShowSuccessMessage("Success!", $"Share successfully.", false);
                return NewtonSoftJsonResult(new RequestOutcome<string> { RedirectUrl = "", Message = "Share successfully.", IsSuccess = true });

            }
            catch (Exception exception)
            {
                return Json(new RequestOutcome<string> { IsSuccess = false, Message = exception?.Message, Data = exception?.StackTrace });
            }
        }


        private FileInfo FeedbackExportExcel(GameGridFeedbackDto feeedbackModel, out string FileName)
        {

            string folder = $"{_hostingEnvironment.WebRootPath}/DYF/{CurrentUser.CompanyId}/EmojiImages/";
            string filePath = "";
            FileName = $"{feeedbackModel.GameName}-{DateTime.Now.ToString("yyyyMMddHHmmssfff")}.xlsx";
            feeedbackModel.EmojiList = weightageService.GetAllActive(CurrentUser.CompanyId);


            int rowNo = 1;
            var newFile = FileOutputUtil.CreateFile($"{feeedbackModel.GameName}-{DateTime.Now.ToString("yyyyMMddHHmmssfff")}.xlsx");
            using (ExcelPackage pack = new ExcelPackage(newFile))
            {

Aaina.Web/Views/Project/Feedback.cshtml
@model LookFeebbackDto
@using Aaina.Common;
@using Newtonsoft.Json;
@{
    ViewData["Title"] = "Feedback";
    int tenant = Convert.ToInt32(HttpContextAccessor.HttpContext.Request.RouteValues["tenant"]);
}




    <script>
    function set(value) {
        return value;
    }
    var allGame = '@Model.GameList' == null ? "" : set(@Html.Raw(JsonConvert.SerializeObject(Model.GameList)));
    var attributeList = '@Model.AttributeList' == null ? "" : set(@Html.Raw(JsonConvert.SerializeObject(Model.AttributeList)));
    var subAttributeList = '@Model.SubAttributeList' == null ? "" : set(@Html.Raw(JsonConvert.SerializeObject(Model.SubAttributeList)));
    var emojiList = '@Model.EmojiList' == null ? "" : set(@Html.Raw(JsonConvert.SerializeObject(Model.EmojiList)));
    var gameFeedbackDetailList = '@Model.GameFeedbackDetails' == null ? "" : set(@Html.Raw(JsonConvert.SerializeObject(Model.GameFeedbackDetails)));
    var isQuentityFeedback = '@Model.SubAttributeList' == null ? "" : set(@Html.Raw(JsonConvert.SerializeObject(Model.SubAttributeList.Any(s=>s.IsQuantity))));

    </script>

<div class="top-Rbox1">
    <div class="top-Ltext">
        <div class="overlap"></div>
        <a href="javascript:void(0);" class="naleftbtn"><span></span></a>
        <div class="top-Ltextli">
            <ul>
                <li>@Model.Game</li>
                <li>/</li>
                <li>Feedback</li>
            </ul>
            <p>@(DateTime.Now.ToString("dd MMMM yyyy"))</p>
        </div>
    </div>
</div>


<div class="top-Rbox1">
    <div class="selctbox">
        <select asp-for="Id" id="lookId" class="form-control" asp-items="@(new SelectList(Model.LookList,"Id","Name"))"> <option>Scheduled Look</option> </select>
        <input type="hidden" asp-for="GameId" />
        
    </div>
</div>

<div id="frm-add-edit-feedback">
    <form asp-action="feedback" asp-controller="Project" asp-area="" asp-route-tenant="@tenant" method="post" autocomplete="off">
        <div id="validation-summary"></div>
        <input type="hidden" name="LookId" value="@Model.Id" />
        <input type="hidden" asp-for="GameId" />
        <input type="hidden" name="id" value="@Model.feedbackId" />
        <input type="hidden" name="IsDraft" id="IsDraft" value="@Model.feedbackId" />
        <input type="hidden" name="TypeId" value="@Model.TypeId" />
        <div id="feedback_atter_data"> </div>

        <div class="middlebox">
            <div class="tablediv tabledivbtn">
                <div class='table-cont' id='table-cont'>
                    <table id="tbl_game" class="table table-striped">
                        <thead></thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>

            <div class="top-Rbox1 botdiv">
                <div class="top-Rbtn">
                    <button class="btn btn-primary btn-submit" id="brndraft" type="button"> Save Draft</button>
                    <button class="btn btn-primary btn-submit" id="btn-submit" type="submit"> Submit</button>
                </div>
            </div>
        </div>

    </form>
</div>


<div aria-hidden="true" aria-labelledby="modal-add-edit-sub_attr_feedback-label" role="dialog" tabindex="-1" id="modal-add-edit-sub_attr_feedback" class="modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div id="frm-add-edit-role" class="box">
                <form method="post" action="/@tenant/role/addedit/4" novalidate="novalidate">

                    <div class="modal-header">
                        <h4 class="modal-title pull-left" id="sub_title"></h4>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    </div>

                    <div class="modal-body box-body">
                        <div id="validation-summary"></div>
                        <input type="hidden" id="attrid" name="attrid" value="">
                        <input type="hidden" id="gameid" name="gameid" value="">
                        <input type="hidden" id="lookattrid" name="lookattrid" value="">

                        <div id="sub_attr_feedback_div"></div>
                    </div>
                    <div class="modal-footer justify-content-between">
                        <button class="btn btn-success" id="btnsubmit" type="button">
                            Submit
                        </button>
                        <button data-dismiss="modal" id="btn-cancel" class="btn btn-default" type="button">Cancel</button>
                    </div>

                </form>
            </div>




        </div>
    </div>
</div>

@section scripts{
    <script src="~/js/Customejs/Project/Feedback.js" asp-append-version="true"></script>
}

Aaina.Web/Views/Project/GameFeebBack.cshtml
@model GameGridFeedbackDto
@using Aaina.Common;
@{
    ViewData["Title"] = "Index";
    int id = ViewBag.id;
}

@{
    int companyId = CurrentUser.CompanyId;
    int tenant = Convert.ToInt32(HttpContextAccessor.HttpContext.Request.RouteValues["tenant"]);
}

<div class="top-Rbox1">
    <div class="top-Ltext">
        <div class="overlap"></div>
        <a href="javascript:void(0);" class="naleftbtn"><span></span></a>
        <div class="top-Ltextli">
            <ul>
                <li>@Model.GameName</li>
                <li>/</li>
                @*<li>Resources</li>
                    <li>/</li>
                    <li><b>HZL Affairs</b></li>*@
            </ul>
            <p>@(DateTime.Now.ToString("dd MMMM yyyy"))</p>
        </div>
    </div>
    <div class="top-Rbtn">
        <a href="javascript:void(0);" data-url="/@tenant/project/Feedback" class="btn btn btn-primary btn_feedback">Feedback</a>

        @*<a href="/@tenant/Common/ShareUsers/?popupurl=/@tenant/project/Share/?lookId=@Model.LookId$attributeId=@Model.AttributeId$filterId=@Model.FilterId" class="btn btn btn-primary" data-toggle="modal" data-backdrop="static" data-keyboard="false" data-target="#modal-share-users">Share</a>*@
        @Html.Partial("_Modal", new Modal { ID = "modal-share-users", AreaLabeledId = "modal-share-users-label", Size = ModalSize.Large })
    </div>
</div>
<div class="top-Rbox1">
    <div class="selctbox">
        <select asp-for="LookId" asp-items="@(new SelectList(Model.LookList,"Id","Name"))"></select>
        <input type="hidden" asp-for="GameId" />
    </div>


</div>
<div class="middlebox">
    <div class="tablediv tabledivbtn">
        <div class='table-cont' id='table-cont'>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th><input type="checkbox" class="all_game_check" /></th>
                        <th scope="col">Games</th>
                        @if (!Model.IsSelf)
                        {
                            <th scope="col">Overall</th>
                        }
                        @foreach (var item in Model.LookGroupList)
                        {
                            <th scope="col">@item.Name</th>
                        }
                    </tr>
                </thead>
                <tbody>
                    @if (Model.AllGames.Any())
                    {
                        int i = 1;
                        @Html.Raw(Url.BindSubRowUser(Model.AllGames, Model, "", "", 0, companyId));
                    }
                    else
                    {
                        <tr>

                            <td colspan="@(Model.LookGroupList.Count+3)">Record not found</td>
                        </tr>
                    }


                </tbody>
            </table>
        </div>
    </div>

    <div id="div_table" style="display:none">
        <style>
            .tablediv .table {
                border: 1px solid #efefef;
                background: #fff;
            }

            .table {
                width: 100%;
                max-width: 100%;
                margin-bottom: 20px;
            }

            table {
                border-collapse: collapse;
                border-spacing: 0;
            }

            tablediv .table tr th {
                background: #e5e5e5;
                border-right: 1px solid #efefef;
                color: #000000;
            }

            .tablediv .table tr th {
                font-size: 15px;
                text-align: center;
                font-weight: 500;
            }

            .table > thead > tr > th {
                vertical-align: bottom;
                border-bottom: 2px solid #ddd;
            }

            .table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td {
                padding: 8px;
                line-height: 1.42857143;
                vertical-align: top;
                border-top: 1px solid #ddd;
            }
        </style>
        <table class="table table-striped">
            <thead>
                <tr>

                    <th scope="col">Games</th>
                    <th scope="col">Overall</th>
                    @foreach (var item in Model.LookGroupList)
                    {
                        <th scope="col">@item.Name</th>
                    }
                </tr>
            </thead>
            <tbody>
                @if (Model.AllGames.Any())
                {
                    int i = 1;
                    @Html.Raw(Url.BindSubRowWithPlus(Model.AllGames, Model, "", "", 0, companyId));
                }
                else
                {
                    <tr>
                        <td colspan="@(Model.LookGroupList.Count+3)">Record not found</td>
                    </tr>
                }


            </tbody>
        </table>
    </div>
    <div class="top-Rbox1 botdiv">
        <div class="switchbtn">
            <label class="switch">
                <input type="checkbox" id="togBtn" checked>
                <div class="slider round">
                    <!--ADDED HTML -->
                    <span class="on">LINKED</span> <span class="off">OFF</span>
                    <!--END-->
                </div>
            </label>
        </div>
        @*<div class="switchbtn">
            <a href="/@tenant/play?v=today" class="btn btn btn-primary btn_feedback">Game Plays</a>
        </div>*@

    </div>
</div>

@section Scripts {
    <script>
        var table;

        function CheckUnChekChild($data) {

            var val = $data.val();
            $(".parent_" + val).prop('checked', $data.is(":checked"));
            $(".parent_" + val).each(function () {
                CheckUnChekChild($(this));
            });
        }

        $(function () {

            $('.all_game_check').on('change').change(function () {
                $(".game_check").prop('checked', $(this).is(":checked"));

            });

            $('.game_check').on('change').change(function () {
                CheckUnChekChild($(this));

            });

            $('a[data-toggle="collapse"]').on('click', function () {
                var objectID = '.' + $(this).attr('id');

                if ($(objectID).hasClass('in')) {
                    $(objectID).removeClass('in');
                    $(this).html('<span class="fa fa-plus-square mtx" ></span>');
                    $(objectID).hide();
                }
                else {
                    $(objectID).addClass('in');
                    $(this).html('<span class="fa fa-minus-circle mtx" ></span>');
                    $(objectID).show();
                }
            });


            $(".btn_feedback").on('click', function () {

                var gameId = $("#GameId").val();
                var lookId = $("#LookId").val();
                var checkedItemsAsString = $('.game_check:checked').map(function () { return $(this).val().toString(); }).get().join(",");
                window.location.href = `/${'@tenant'}/project/Feedback?lookId=${lookId}&pid=${checkedItemsAsString}`;
            });

            $("#LookId").on('change', function () {
                var lookId = $(this).val();
                var gameId = $("#GameId").val();
                window.location.href = `/${'@tenant'}/project/gamefeebback?lookId=${lookId}`;
            });

        });
    </script>

}

Aaina.Web/Views/Project/Index.cshtml
@model List<GameDto>
@{
    ViewData["Title"] = "Index";
    int tenant = Convert.ToInt32(HttpContextAccessor.HttpContext.Request.RouteValues["tenant"]);
}

<section class="content">

    <div class="box">
        <div class="box-body table-responsive">
            <div class="col-sm-12">
                <div class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                    <div class="row">
                        <div class="col-sm-12">
                            <table class="table table-bordered table-hover dataTable no-footer">

                                <thead>
                                    <tr>
                                        <th>S.No</th>

                                        <th>Name</th>
                                        <th>Contact Person</th>
                                        <th>Clent</th>
                                        <th>Location</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model.Any())
                                    {
                                        int i = 1;
                                        foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>
                                                    @i
                                                </td>

                                                <td>
                                                    @item.Name
                                                </td>
                                                <td>@item.ContactPerson</td>
                                                <td>@item.ClientName</td>
                                                <td>@item.Location</td>
                                                <td>
                                                    @if (CurrentUser.RoleId == (int)Aaina.Common.UserType.User)
                                                    {
                                                    <a href="/@tenant/project/feedback" class="btn btn-sm btn-success mg-l-5"> Feedback </a>
                                                    }
                                                </td>
                                            </tr>
                                            i++;

                                        }
                                    }

                                </tbody>
                            </table>

                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>